### PR TITLE
Fix BST/DST check bug, update docs, add test

### PR DESCRIPTION
**Pull request by smittytone**

### CODE REVIEW

**Comment by smittytone** [comment]
@betzrhodes spotted a nasty bug this weekend, which I have fixed and tested. Also updated one the methods and added a test for that too. All pass. Be good to get this out pronto, as it'll impact anyone watching out for the coming daylight time saving switch-over

**Comment by betzrhodes** [comment]
I just tried running the tests - they are failing for me.

**Comment by betzrhodes** [comment]
Found the issue - I wasn't testing on an imp004m. I've updated the tests and added a testing config file, so tests can be added to our automated testing system.

**Comment by betzrhodes** [comment]
automated testing is set up and all tests are now passing

**Review by betzrhodes — APPROVED** [review]

**Comment by betzrhodes** [comment]
Looks good I'll let you merge. Ping me when you want to publish.

**Comment by smittytone** [comment]
@betzrhodes much better test code -- thank you! I'll merge this to master

**Pull request merged**
