### PR TITLE
3.0.0: Remove debugI2C() function

### PR DESCRIPTION
**Pull request by smittytone**
See https://forums.electricimp.com/t/c001-i2c-issues-but-imp004m-works/6101/4

### CODE REVIEW

**Comment by smittytone** [comment]
See the linked forum post from Hugo. I've removed the function, and bumped the library to 3.0.0, but I'm wondering if we should just deprecate and archive the library. I only created for personal use, really, and it's lacked love since I lost the ability to update the version on the server.
If we *don't* kill it, should I add in more of the stuff from here: https://github.com/smittytone/generic/blob/master/utilities.nut
This is the version I use these days

**Comment by betzrhodes** [comment]
It's up to you. I don't mind updating the library. There are a number of folks using it, and it is a helpful collection of functions.

**Review by betzrhodes — APPROVED** [review]

**Comment by smittytone** [comment]
OK. I've added a set of new functions, updated the Read Me to match the current style, and added a test case (which passes). Anything else I need to do, d'you think, @betzrhodes ?

**Comment by betzrhodes** [comment]
I think this looks good. Thanks!

**Pull request merged**
